spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/endonekm?serverTimezone=UTC
    username: root
    password:
mybatis:
  mapper-locations: classpath:mapper/*.xml