server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.238.128:8080
    nacos:
        server-addr: 192.168.238.128:8848
        discovery:
          username: nacos
          password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"

            allowedMethods: "*"

            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

      routes:
        - id: admin-server
          uri: lb://admin-server
          predicates:
            - Path=/admin/**


        - id: siteM-post-server
          uri: lb://siteM-server
          predicates:
              - Path=/post/**


        - id: siteM-transfer-server
          uri: lb://siteM-server
          predicates:
              - Path=/transfer/**



        - id: oss-server
          uri: lb://oss-server
          predicates:
              - Path=/oss/**


        - id: post-express-server
          uri: lb://express-server
          predicates:
              - Path=/postExpress/**

        - id: transfer-express-server
          uri: lb://express-server
          predicates:
              - Path=/transferExpress/**